# Generated by Django 5.1.2 on 2025-01-09 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0003_registration_unique_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
