# Generated by Django 5.1.2 on 2025-01-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0004_module_registered_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='registered_users',
        ),
    ]
