# Generated by Django 5.1.2 on 2025-01-09 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0005_remove_module_registered_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='registered_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
