# Generated by Django 5.1.2 on 2025-01-09 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0006_module_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='students',
        ),
        migrations.AddField(
            model_name='module',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
